
export enum DisconnectReason {
    CONNECTIONREASON_TIMEOUT,
    CONNECTIONREASON_LOST,
    CONNECTIONREASON_REFUSED,
    CONNECTIONREASON_NETWORK_DATA_ERROR,
    CONNECTIONREASON_CRYPTO_ERROR,
    CONNECTIONREASON_INVALID_DATA,
    CONNECTIONREASON_INVALID_NICKNAME,
    CONNECTIONREASON_INVALID_VERSION,
    CONNECTIONREASON_DISCONNECTED,
    CONNECTIONREASON_SERVER_FULL,
    CONNECTIONREASON_INVALID_PASSWORD,
    CONNECTIONREASON_KICKED,
    CONNECTIONREASON_BANNED,
};